// Common UI Components
export { default as BaseButton } from './BaseButton.vue'
export { default as BaseCard } from './BaseCard.vue'
export { default as BaseInput } from './BaseInput.vue'
export { default as BaseModal } from './BaseModal.vue'

// Re-export Element Plus components for convenience
export {
  ElButton,
  ElCard,
  ElInput,
  ElDialog,
  ElForm,
  ElFormItem,
  ElSelect,
  ElOption,
  ElCheckbox,
  ElRadio,
  ElSwitch,
  ElSlider,
  ElDatePicker,
  ElTimePicker,
  ElUpload,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElTabs,
  ElTabPane,
  ElCollapse,
  ElCollapseItem,
  ElTree,
  ElMenu,
  ElMenuItem,
  ElSubMenu,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElSteps,
  ElStep,
  ElAlert,
  ElMessage,
  ElMessageBox,
  ElNotification,
  ElLoading,
  ElIcon,
  ElTooltip,
  ElPopover,
  ElDropdown,
  ElDropdownMenu,
  ElDropdownItem,
  ElDrawer,
  ElBacktop,
  ElAffix,
  ElInfiniteScroll,
  ElScrollbar,
  ElCarousel,
  ElCarouselItem,
  ElImage,
  ElAvatar,
  ElBadge,
  ElTag,
  ElProgress,
  ElSkeleton,
  ElEmpty,
  ElResult,
  ElDescriptions,
  ElDescriptionsItem,
  ElTimeline,
  ElTimelineItem,
  ElDivider,
  ElSpace,
  ElRow,
  ElCol,
  ElContainer,
  ElHeader,
  ElAside,
  ElMain,
  ElFooter
} from 'element-plus'
