spring:
  application:
    name: cosmos-agent
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmos_agent
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # MyBatis-Plus Configuration
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
    global-config:
      db-config:
        table-prefix: ""
        id-type: auto
  
  # Server Configuration
  server:
    port: 8080
  
  # CORS Configuration
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  
  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
        base-path: /actuator
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
    info:
      env:
        enabled: true
      build:
        enabled: true
      git:
        enabled: true

# Application Info
info:
  app:
    name: cosmos-agent
    version: 1.0.0
    description: AI Agent Workflow Management System
  author: Chuguo Tech
  build:
    time: ${build.time}
    version: ${project.version}